trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- script: |
   npm i -g karma-cli
   npm install
  displayName: 'npm install'

- script: 'npm audit fix'
  displayName: 'npm audit fix'

- script: 'karma start test\karma.conf.js'
  displayName: 'karma start'