pool:
  name: Hosted VS2017
steps:
- script: |
   npm i -g karma-cli
   npm install
  displayName: 'npm install'

- script: 'npm audit fix'
  displayName: 'npm audit fix'

- script: 'karma start test\karma.conf.js'
  displayName: 'karma start'