pool:
  name: Hosted VS2017
steps:
- script: |
   npm i -g npm
   npm i -g yarn
   npm i --save bootstrap@latest
   npm i --save jquery@latest
   npm i --save-dev karma@3.0.0
   npm install
  displayName: 'npm install'

- script: 'npm audit fix'
  displayName: 'npm audit fix'