trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
  
- script: |
   npm i -g karma-cli
   npm i -g concurrently
   npm i -g protractor
   npm i -g webdriver-manager
   npm install
  displayName: 'npm install'

- script: 'npm audit fix'
  displayName: 'npm audit fix'

- script: 'karma start test/karma.conf.js'
  displayName: 'karma unit tests'

- script: |
   webdriver-manager clean
   webdriver-manager update --chrome
  #  webdriver-manager start --detach
  #  protractor test/protractor.conf.js
   webdriver-manager shutdown
   webdriver-manager clean
  displayName: 'protractor end to end tests'
